## Практическое задание №5


**5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое
внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5𝐸)^-1, где E - единичная матрица размера 5х5.**


In [66]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank

In [67]:
e = 5*np.identity(5)
print(inv(e))

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


**5.2. Вычислите определитель:[[1,2,3],[4,0,6],[7,8,9]]**

In [68]:
m = np.array([[1,2,3],[4,0,6],[7,8,9]]) 
det(m)

59.999999999999986

**5.3.1. Вычислите матрицу, обратную данной:[[1,2,3],[4,0,6],[7,8,9]]**

In [69]:
m = np.array([[1,2,3],[4,0,6],[7,8,9]]) 
print(inv(m))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


**5.3.2. Приведите пример матрицы 4х4, ранг которой равен 1.**

In [70]:
n = np.array([[1,0,0,0],[0,0,0,0],[0,0,0,0], [0,0,0,0]]) 
print(n, end='\n\n')
print(f'Ранг = {matrix_rank(n)}')

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Ранг = 1


**5.4.Вычислите скалярное произведение двух векторов: (1, 5) и (2, 8)**

In [76]:
a = np.array([1,5]) 
b = np.array([2,8])
print(f'Скалярное произведение векторов = {np.inner(a, b)}')

Скалярное произведение векторов = 42


**5.5. Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3)**

In [77]:
a = np.array([1,5,0]) 
b = np.array([2,8,7])
c = np.array([7,1.5,3])
print(f'Смешанное произведение векторов = {np.inner(np.cross(a,b), c)}')

Смешанное произведение векторов = 228.5
