## Практическое задание №6

In [39]:
import numpy as np
from numpy.linalg import solve, lstsq
from scipy.linalg import lu
import warnings

warnings.filterwarnings('ignore')

**1. Решите линейную систему:[[1,2,3],[4,0,6],[7,8,9]] * X = [12,2,1]**

In [9]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]])
b = np.array([12,2,1])
print(solve(a,b))

[-9.2         0.9         6.46666667]


**2. Найдите псевдорешение:
{x + 2y – z = 1, 
3x – 4y = 7, 
8x – 5y + 2z = 12, 
2x – 5z = 7, 
11x +4y – 7z = 15}**

In [16]:
a = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
b = np.array([1,7,12,7,15])
print(lstsq(a,b))

(array([ 1.13919353, -0.90498444, -0.9009803 ]), array([0.71523211]), 3, array([15.2817306 ,  9.59852942,  3.65197794]))


In [18]:
# Проверка решения
print(np.dot(a, [1.13919353, -0.90498444, -0.9009803]))

[ 0.23020495  7.03751835 11.83650984  6.78328856 15.21805317]


**3. Сколько решений имеет линейная система:[[1,2,3],[4,5,6],[7,8,9]] * X = [12,2,1] ? Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.**

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([12,2,1])
print(solve(a,b))

[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]


Данная система не имеет решений (решение численным методом дает значения порядка 10^16). Заменим свободный член во всех уравнениях на 0 и решим новую систему:

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([0,0,0])
print(solve(a,b))

[ 0.  0. -0.]


Новая система имеет бесконечно много решений. Общее решение: x2 = -2*x1, x3 = x1. Численный метод нашел только одно из решений.

**4. Вычислите LU-разложение матрицы: [[1,2,3],[2,16,21],[4,28,73]]**

In [40]:
a = np.array([[1,2,3],[2,16,21],[4,28,73]])
p,l,u = lu(a)
print(p, end='\n\n')
print(l, end='\n\n')
print(u)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
